### ISSUE TITLE
Make FAB button hide automatically

### ISSUE THREAD

**Issue by TsukihiAraragi** [xz-dev/UpgradeAll#3]
Sometimes, update button  will be covered with FAB button, like this ![](https://i.imgur.com/rjP6nYY.png)

**Comment by xz-dev** [comment]
This issue has been resolved. 
[https://github.com/xz-dev/UpgradeAll/commit/1a461a29a8f1ea9bfb4c2693ef7826ee5e887bf8](url)
Please download the latest version
https://github.com/xz-dev/UpgradeAll/releases/tag/0.0.9
